coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%

ignore:
  - "src/test/"

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: no
      macro: no
