# We should be able to avoid the cost of running this action by using custom
# images. Do not include anything in this action, like checking out the
# repository, that cannot be fixed in an image.
name: configure Unix environment
runs:
  using: composite
  steps:
    - name: install Ninja on Linux
      if: matrix.generator == 'Ninja' && runner.os == 'Linux'
      shell: bash
      run: sudo apt install ninja-build
    - name: install Ninja on OSX
      if: matrix.generator == 'Ninja' && runner.os == 'macOS'
      shell: bash
      run: brew install ninja
    - name: install nproc on OSX
      if: runner.os == 'macOS'
      shell: bash
      run: brew install coreutils
    - name: choose Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: learn Python cache directory
      id: pip-cache
      shell: bash
      run: |
        sudo pip install --upgrade pip
        echo "::set-output name=dir::$(pip cache dir)"
    - name: restore Python cache directory
      uses: actions/cache@v2
      with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('.github/actions/setup-nix/action.yml') }}
    - name: install Conan
      run: pip install wheel conan
    - name: check environment
      shell: bash
      run: |
        echo ${PATH} | tr ':' '\n'
        python --version
        conan --version
        cmake --version
        env
    - name: configure Conan
      shell: bash
      run: conan profile new default --detect
    - name: configure Conan on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: learn Conan cache directory
      id: conan-cache
      shell: bash
      run: |
        echo "::set-output name=dir::$(conan config get storage.path)"
    - name: restore Conan cache directory
      uses: actions/cache@v2
      with:
          path: ${{ steps.conan-cache.outputs.dir }}
          key: ${{ hashFiles('~/.conan/profiles/default', 'conanfile.py', 'external/*', '.github/actions/setup-nix/action.yml') }}
