name: nix
on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - macos
        generator:
          - Ninja
        configuration:
          - Release
    runs-on: ${{ matrix.platform }}-latest
    env:
      build_dir: .build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure environment
        uses: ./.github/actions/setup-nix
      - name: build
        uses: ./.github/actions/build
      - name: test
        run: |
          ${build_dir}/rippled --unittest --unittest-jobs $(nproc)
